# Generated by Django 4.1.5 on 2023-06-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendingPhysicianUser',
            fields=[
                ('physician_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('department_physician', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('doctor_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('department_doctor', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_username', models.CharField(max_length=30)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('verification', models.CharField(choices=[('success', 'Success'), ('fail', 'Fail')], default='success', max_length=7)),
                ('login_stats', models.CharField(default='logged in', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NurseUser',
            fields=[
                ('nurse_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='fname', max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('department_nurse', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='otp_num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientUser',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('ic', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=50)),
                ('name_emergency', models.CharField(max_length=50)),
                ('emergency_number', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('discharged', 'Discharged')], default='discharged', max_length=10)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistUser',
            fields=[
                ('receptionist_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('given', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vitalSignClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('respiratory', models.IntegerField(default=0)),
                ('diastolic', models.IntegerField(default=0)),
                ('systolic', models.IntegerField(default=0)),
                ('pulse', models.IntegerField(default=0)),
                ('datetime_vitalsign', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='treatmentPlanClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=400)),
                ('duration', models.IntegerField(default='0')),
                ('duration_unit', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=5)),
                ('plan_description', models.CharField(max_length=400)),
                ('additional_note', models.CharField(default='', max_length=400)),
                ('medication_name', models.CharField(default='', max_length=100)),
                ('prescription', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='medicalRecordClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_list', models.CharField(default='', max_length=50)),
                ('additional_surgery', models.CharField(blank=True, max_length=50, null=True)),
                ('surgery_year', models.CharField(default='', max_length=4)),
                ('additional_year', models.CharField(blank=True, max_length=4, null=True)),
                ('allergies', models.CharField(default='', max_length=50)),
                ('additional_allergy', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='billClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('pharmacy_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('doctor_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('credit_card', models.CharField(default='', max_length=150)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
        migrations.CreateModel(
            name='admissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('doctor_name', models.CharField(max_length=50)),
                ('physician_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=30)),
                ('visit_type', models.CharField(choices=[('IPD', 'IPD'), ('OPD', 'OPD')], max_length=3)),
                ('room_no', models.CharField(default='', max_length=3)),
                ('admitted_date', models.DateTimeField(auto_now_add=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.patientuser')),
            ],
        ),
    ]
