# Generated by Django 4.1.5 on 2023-06-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionclass',
            name='room_no',
        ),
    ]
