# Generated by Django 4.1.5 on 2023-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_remove_admissionclass_room_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionclass',
            name='room_no',
            field=models.CharField(default='', max_length=3),
        ),
    ]
